### PR TITLE
[FW][FIX]base_report_to_print_node: patch for OCA

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/miscellaneous#224

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/226).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this PR targets 18.0 and is the last of the forward-port chain containing:
* ingadhoc/miscellaneous#225

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
