### PR TITLE
[FIX]base_report_to_print_node: patch for OCA

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/224).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#225
- ingadhoc/miscellaneous#226

**Pull request closed without merging**
