### PR TITLE
[IMP] portal_holidays: new module

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/101).

**Comment by matiasperalta1** [comment]
@nicomacr Nico, tenes alguna idea de por qué esta fallando el módulo, no entiendo el mensaje de error

**Comment by nicomacr** [comment]
@matiasperalta1 el error con personalizaciones es por una personalizacion de boggio que rompe otras,  los demás dan todo bien los test

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@matiasperalta1 @nicomacr because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#103

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#103

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#112

**Pull request closed without merging**
