### PR TITLE
[FW][FIX] portal_holidays: portal users didn´t see Leaves menu

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/miscellaneous#117

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/118).

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 cherrypicking of pull request ingadhoc/miscellaneous#117 failed.

stdout:
```
Auto-merging portal_holidays/security/portal_holidays.xml
CONFLICT (content): Merge conflict in portal_holidays/security/portal_holidays.xml
Auto-merging portal_holidays/__manifest__.py
CONFLICT (content): Merge conflict in portal_holidays/__manifest__.py

```

stderr:
```
15:24:58.800895 git.c:439               trace: built-in: git cherry-pick a67d42c90b9dbe642b26b5071e87d9640c437212
error: could not apply a67d42c... [FIX] portal_holidays: portal users didn´t see Leaves menu
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by augusto-weiss** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/118).

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss I can only do this on forward-port PRs and this is not one, see roboadhoc.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
