### PR TITLE
[FIX] transifex_push: fix transifex push

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/200).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @vib-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
