### PR TITLE
[MIG] portal_timesheet_attendance: Migration to 18.0

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/230).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: you can't review+.

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @ced-adhoc. I'm afraid I can't do that.

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
