### PR TITLE
Revert "[REM] crm_mail_tracking: remove module"

### PR DESCRIPTION
**Pull request by jjscarafia**
This reverts commit a24d3daa3e1f255e96584591f543de3c4eb21e66.

### CODE REVIEW

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc ignore

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/212).

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Pull request closed without merging**
