### PR TITLE
[FIX] portal_backend: demo data fix

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/125).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@Bruno-Zanotti you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you are not allowed to override this status.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
