### PR TITLE
[FW][FIX]maintenance_ux:change email_to

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/miscellaneous#188

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/190).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc cherrypicking of pull request ingadhoc/miscellaneous#188 failed.

stdout:
```
On branch 17.0-16.0-h-71689-jc-1-WpvB-fw
You are currently cherry-picking commit 3bb8fec.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean

```

stderr:
```
12:38:07.444767 git.c:444               trace: built-in: git cherry-pick 3bb8fec5176d2bbe62a51cced2f4467622db701c
12:38:07.448649 run-command.c:664       trace: run_command: git commit -n --no-gpg-sign -F .git/MERGE_MSG --cleanup=verbatim --allow-empty-message
12:38:07.449782 git.c:444               trace: built-in: git commit -n --no-gpg-sign -F .git/MERGE_MSG --cleanup=verbatim --allow-empty-message
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by mav-adhoc** [comment]
@jcadhoc Fijate este fwp!

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Pull request closed without merging**
