### PR TITLE
[FW][ADD]base_ux: fantasy name in res_partner form view

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/miscellaneous#86

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/88).

**Comment by fw-bot-adhoc** [comment]
Ping @PabloPaezSheridan, @nicomacr
While this was properly forward-ported, at least one co-dependent PR (ingadhoc/odoo-argentina#586) did not succeed. You will need to fix it before this can be merged.

Both this PR and the others will need to be approved via `@roboadhoc r+` as they are all considered "in conflict".

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Linked pull request(s) ingadhoc/odoo-argentina#586 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
