### PR TITLE
[FW][FIX]base_report_to_print_node: patch for OCA

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/miscellaneous#224

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/225).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @nicomacr this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@nicomacr I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
