### PR TITLE
[FIX] portal_holidays: portal users didn´t see Leaves menu

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/117).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#118

**Pull request closed without merging**
