### PR TITLE
[MIG] portal_backend: Migration to 16.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/116).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/116).

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you can't review+.

**Comment by roboadhoc** [comment]
@Bruno-Zanotti I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
