### PR TITLE
[FIX] portal_timesheet: fix access of internal users

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/miscellaneous/pull/105).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/miscellaneous#106

**Pull request closed without merging**
