### PR TITLE
[FIX] portal_timesheet: add new record rules

### PR DESCRIPTION
**Pull request by ced-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/193).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/miscellaneous#195

**Pull request closed without merging**
