### PR TITLE
[FIX] portal_backend: update of user groups view fixed

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/192).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@Bruno-Zanotti you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you are not allowed to override this status.

**Comment by roboadhoc** [comment]
@lef-adhoc @Bruno-Zanotti linked pull request(s) ingadhoc/sale#803 not ready. Linked PRs are not staged until all of them are ready.

**Pull request merged**
